### ISSUE TITLE
Panic with positive lookahead

### ISSUE THREAD

**Issue by mdabek** [rust-lang/regex#363]
Using positive lookahead in the regexp causes the panic:

Example:
`let re = Regex::new(r"(?=^.{0,253}$)").unwrap();`

Outcome:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("Error parsing regex near \'(?=^.0,\' at character offset 2: Unrecognized flag: \'=\'. (Allowed flags: i, m, s, U, u, x.)")', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
```

**Comment by BurntSushi** [comment]
Note that this isn't a panic in the regex library. The regex parser is returning an error. The error message tells you that the syntax is incorrect.

From the README:

> Its syntax is similar to Perl-style regular expressions, but **lacks a few features like look around** and backreferences.
